### PR TITLE
Internal function add Mist Flood Lube

### PR DESCRIPTION
**Pull request by alkabal**
Added Mist Flood Lube like you done the reverse/forward function for spindle

Lube attached to macro2
Flood attached to macro15
Mist attached to macro16

compilation ok, work ok

### CODE REVIEW

**Comment by alkabal** [comment]
Hi

You does not want to add this feature ?

Best regards

**Comment by rubienr** [comment]
Sorry for the late reply: due to lack of time the development is still on hold until Nov./Dec. 19'. Will fix minor driver issues and create a pull-request and come back to your request.

**Comment by rubienr** [comment]
Flood/mist look good!

* Is is possible to map flood/mist to some of these macros: 1-4, 5, 6, 8, 9, 11-16? Currently macros 5 and 7 would make more sense for switching the display view in between machine coordinates and work-piece coordinates.
   * If possible squash the commits to one (create new branch, `git checkout` new branch, `git merge --squash feature-xhc-whb04b-6`, `git add` files except of `hal_gpio_h3_demo.hal`).
* The pull request for `src/hal/drivers/hal_gpio_h3_demo.hal` would better match to https://github.com/machinekit/machinekit.

**Comment by alkabal** [comment]
Hi

I have do the job with macro 2/15/16 

But at same time I have mistakenly merge absolue/relative toggle to button safeZ

You can revert this parts If you think is only better for my Pearsonal  use (G92.1 macro5, G92.2 macro6, G92.1 macro7, G92 macro9)



Br

**Pull request closed without merging**
